// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5raz7OaAjFv2dkXjDoyafbO_GBNYrQj4',
    appId: '1:482881915289:web:17045588e05be260c4eb08',
    messagingSenderId: '482881915289',
    projectId: 'hero-location-4b362',
    authDomain: 'hero-location-4b362.firebaseapp.com',
    storageBucket: 'hero-location-4b362.firebasestorage.app',
    measurementId: 'G-5NZ4F789XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1XPh0OJ-kBWc5XYB7Vw9wwj7Av5w6kR4',
    appId: '1:482881915289:android:08556a048a1e887ac4eb08',
    messagingSenderId: '482881915289',
    projectId: 'hero-location-4b362',
    storageBucket: 'hero-location-4b362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1EIzGyZwFWel-Ovra6HhF3Cggb5lA2hE',
    appId: '1:482881915289:ios:f51bcbb203a5ce34c4eb08',
    messagingSenderId: '482881915289',
    projectId: 'hero-location-4b362',
    storageBucket: 'hero-location-4b362.firebasestorage.app',
    iosBundleId: 'com.example.heroLocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1EIzGyZwFWel-Ovra6HhF3Cggb5lA2hE',
    appId: '1:482881915289:ios:f51bcbb203a5ce34c4eb08',
    messagingSenderId: '482881915289',
    projectId: 'hero-location-4b362',
    storageBucket: 'hero-location-4b362.firebasestorage.app',
    iosBundleId: 'com.example.heroLocation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5raz7OaAjFv2dkXjDoyafbO_GBNYrQj4',
    appId: '1:482881915289:web:590a187615d4962bc4eb08',
    messagingSenderId: '482881915289',
    projectId: 'hero-location-4b362',
    authDomain: 'hero-location-4b362.firebaseapp.com',
    storageBucket: 'hero-location-4b362.firebasestorage.app',
    measurementId: 'G-GFBH5F736Z',
  );

}